spring.application.name=devwall_backend
server.servlet.context-path=/api
server.port=1400
ai.ip=https://duckduckgo.com/duckchat/v1/chat
ai.generate=D


#DB
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://alpha.europe.mkdb.sh:5432/lskkmxgy?createDatabaseIfNotExist=true
spring.datasource.username=hcdydtcr
spring.datasource.password=uqnidlonsavxydwgixtj
spring.datasource.driver-class-name=org.postgresql.Driver
org.hibernate.dialect=hibernate.dialect.PostgreSQLDialect

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true